agentFinder/urls.py
from django.urls import path

from . import views
app_name = 'agentFinder'


urlpatterns = [
    path('', views.index, name='index'),
    path('Selling/', views.selling, name='selling'),
    path('Buying/', views.buying, name='buying'),
    path('Terms/', views.terms, name='terms'),
    path('Privacy/', views.privacy, name='privacy'),
    path('Testimonials/', views.client, name='client'),
    path('Seller_Info_Saved/', views.selling_forms_save, name='selling_forms_save'),
    path('Buyer_Info_Saved/', views.buying_forms_save, name='buying_forms_save'),
    path('saved/', views.namephoneinfo_save, name='namephoneinfo_save'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('agentFinder.urls'))
]

agentFinder/models.py
from django.contrib import admin
from django.db import models
# Create your models here.

class sellerInfo(models.Model):
    address = models.TextField()
    propertType = models.TextField()
    targetSale = models.TextField()
    SoonTime = models.TextField()
    name = models.TextField()
    phone = models.TextField()
    email = models.TextField()
    def __str__(self):
        return self.name

admin.site.register(sellerInfo)

class buyerInfo(models.Model):
    address = models.TextField()
    propertType = models.TextField()
    targetSale = models.TextField()
    SoonTime = models.TextField()
    name = models.TextField()
    phone = models.TextField()
    email = models.TextField()
    def __str__(self):
        return self.name

admin.site.register(buyerInfo)

class namephoneInfo(models.Model):
    name = models.TextField()
    phone = models.TextField()

    def __str__(self):
        return self.name

admin.site.register(namephoneInfo)

agentFinder/views.py
from django.shortcuts import render
import json
from .models import sellerInfo, buyerInfo, namephoneInfo
from django.core.mail import send_mail
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

# Create your views here.

def index(request):
    return render(request, 'agentFinder/index.html')

def selling(request):

    return render(request, 'agentFinder/forms.html')

def buying(request):

    return render(request, 'agentFinder/buying.html')

def selling_forms_save(request):
    print("hello")
    print(request.method)

    addr = request.POST.get('address')
    pt = request.POST.get('properType')
    ts = request.POST.get('tgSale')
    st = request.POST.get('soonTime')
    fn = request.POST.get('fname')
    fe = request.POST.get("email")
    fm = request.POST.get("phone")
    try:
        databaseobj = sellerInfo(address=addr, propertType=pt, targetSale=ts,SoonTime=st,
                                name=fn, phone=fm, email=fe)
        databaseobj.save()

    except Exception as e:
        print(str(e))

    data={"Address": addr,
          "Prperty_type": pt,
          "Target_sale": ts,
          "Time":st,
          "Nmae": fn,
          "Email": fe,
          "Number": fm
          }
    msg=json.dumps(data,indent=8)
    print(msg.strip(' {}"", '))
    # send_mail(
    #     "Seller Info",
    #     msg.strip(' {}"", '),
    #     "usamarana845@gmail.com",
    #     ["ranausama12@hotmail.com"],
    #
    # )
    name=fn.split(" ")
    print(name[0])
    context={
        "Name": name[0],
    }
    return render(request, 'agentFinder/forms.html',context)


def buying_forms_save(request):
    print("hello")
    print(request.method)

    addr = request.POST.get('address')
    pt = request.POST.get('properType')
    ts = request.POST.get('tgSale')
    st = request.POST.get('soonTime')
    fn = request.POST.get('fname')
    fe = request.POST.get("email")
    fm = request.POST.get("phone")
    try:
        databaseobj = buyerInfo(address=addr, propertType=pt, targetSale=ts,SoonTime=st,
                                name=fn, phone=fm, email=fe)
        databaseobj.save()

    except Exception as e:
        print(str(e))

    data = {"Address": addr,
            "Prperty_type": pt,
            "Target_sale": ts,
            "Time": st,
            "Nmae": fn,
            "Email": fe,
            "Number": fm
            }
    msg = json.dumps(data, indent=8)
    print(msg.strip(' {}"", '))
    print("buyer")
    # send_mail(
    #     "Seller Info",
    #     msg.strip(' {}"", '),
    #     "usamarana845@gmail.com",
    #     ["ranausama12@hotmail.com"],
    #
    # )
    name = fn.split(" ")
    context = {
        "Name": name[0],
    }
    return render(request, 'agentFinder/buying.html',context)


def namephoneinfo_save(request):
    print(request.method)
    fn = request.POST.get('name')
    fm = request.POST.get('number')
    try:
        databaseobj = namephoneInfo(name=fn, phone=fm)
        databaseobj.save()

    except Exception as e:
        print(str(e))
    data = {
            "Nmae": fn,
            "Number": fm
            }
    msg = json.dumps(data, indent=3)
    print(msg.strip(' {}"", '))
    # name = fn.split(" ")
    return render(request, 'agentFinder/index.html')

def terms(request):

    return render(request, 'agentFinder/terms.html')

def privacy(request):

    return render(request, 'agentFinder/privacy.html')

def client(request):

    return render(request, 'agentFinder/client.html')

agentFinder/templates/agentFinder/buying.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Buying</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'agentFinder/fonts/material-icon/css/material-design-iconic-font.min.css' %}" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'agentFinder/style/styleform.css' %}" >
</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="row" >
						<nav>
						<div class="col-md-auto">
					<div class="branding"  >
						<a href="{% url 'agentFinder:index' %}">
						<img class="imglogo" src="{% static 'agentFinder/images/logo.png' %}" alt="Apartments" >
						<h1 class="site-title"><a>SearchMyAgent</a></h1>
						<small class="site-description">Live better</small>
							</a>
					</div>
							</div>
						</nav>
					</div>
        </div>
    </header>

    <div class="main">
   <!-- MultiStep Form -->
{% if Name %}
		<div class="container">
			<div class="row justify-content-center">
				<h1  class="headtitle head " >Thanks {{ Name }}!</h1>
             </div>
			<div class="row justify-content-center">
				<p class="tagline tag">We recived your information and will respond shortly</p>
             </div>
			</div>
{% else %}
<form id="booking-form" action="{% url 'agentFinder:buying_forms_save' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

	<div class="formcontent">
		<div class="tab-content">
			<div class="tab-pane" id="step1">
				<ul>
					<li>
            <label>Where are you looking to buy?</label>
            <div class="errorTxt"></div>
            <input type="text" name="address" placeholder="Enter address, city, zip or neighborhood">
				 </li>
				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn1" type="button">Prev</button>
						<button class="next-btn next-btn1" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step2">
				<ul>
					<li>
            <label>What type of property are you looking to buy?</label>
            <div class="errorTxt"></div>
            <select name="properType" required>
              <option value="">Select</option>
              <option value="Single Family">Single Family</option>
              <option value="Condo">Condo</option>
              <option value="land or lot">land or lot</option>
              <option value="Mobile Home">Mobile Home</option>
              <option value="Townhome">Townhome</option>
              <option value="Commercial">Commercial</option>

					</select>
				 </li>
				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn2" type="button">Prev</button>
						<button class="next-btn next-btn2" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step3">
				<ul>
					<li>
            <label>What is your budget?</label>
            <div class="errorTxt"></div>
            <select name="tgSale" required>
              <option value="">Select</option>
              <option value="$50k-$100k">$50k-$100k</option>
              <option value="$100k-$150k">$100k-$150k</option>
              <option value="$150k-$200k">$150k-$200k</option>
              <option value="$200k-$250k">$200k-$250k</option>
              <option value="$250k-$300k">$250k-$300k</option>
              <option value="$300k-$350k">$300k-$350k</option>
              <option value="$350k-$400k">$350k-$400k</option>
              <option value="$400k-$450k">$400k-$450k</option>
              <option value="$450k-$500k">$450k-$500k</option>
              <option value="$500k-$550k">$500k-$550k</option>

					</select>
				 </li>
				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn3" type="button">Prev</button>
						<button class="next-btn next-btn3" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step4">
				<ul>

					<li>
            <label>How soon are you looking to buy?</label>
            <div class="errorTxt"></div>
            <select name="soonTime">
              <option value="">Select</option>
              <option value="0-3 Months">0-3 Months</option>
				<option value="3-6 Months">3-6 Months</option>
				<option value="6-12 Months">6-12 Months</option>
				<option value="Over 1 Year">Over 1 Year</option>
            	  </select>
				  </li>

					<li class="buttons">
						<button class="prev-btn prev-btn4" type="button">Prev</button>
						<button class="next-btn next-btn4" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step5">
				<ul>


					<li>
            <label>Let's connect you with the best agent in your area</label>
            <div class="errorTxt"></div>
            <input type="text" name="fname" placeholder="Full Name">
          </li>
					<li>
						<div class="errorTxt"></div>
					  <input type="text" name="phone" placeholder="Phone">
					</li>
					<li>
						<div class="errorTxt"></div>
					  <input type="email" name="email" placeholder="email">
					</li>
					<li>
						<button class="prev-btn prev-btn5" type="button">Prev</button>
						<button class="submit-btn" type="submit">Find an Agent</button>
					</li>
				</ul>
			</div>
		</div>

		<div class="progress-wrap">
			<div class="line-progress-bar">
				<div class="line"></div>
				<ul class="checkout-bar">
					<li class="progressbar-dots active"><span>step 1</span></li>
					<li class="progressbar-dots"><span>step 2</span></li>
					<li class="progressbar-dots"><span>Final step</span></li>
				</ul>
			</div>
		</div>

		<div id="loader" style="display: none;">
			<img src="//d2erq0e4xljvr7.cloudfront.net/assets/img/ring.svg">
		</div>
		</div>
	</form>
<!-- /.MultiStep Form -->
{% endif %}

    <!-- JS -->

    <script src="{% static 'agentFinder/js/main.js' %}" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

agentFinder/templates/agentFinder/forms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Selling</title>

    <link rel="stylesheet" href="{% static 'agentFinder/fonts/material-icon/css/material-design-iconic-font.min.css' %}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>

	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyCCjFJ3h143czn6rJ4Yu2p8f6p6cjywv80"></script>


    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'agentFinder/style/styleform.css' %}" >
</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="row" >
						<nav>
						<div class="col-md-auto">
					<div class="branding"  >
						<a href="{% url 'agentFinder:index' %}">
						<img class="imglogo" src="{% static 'agentFinder/images/logo.png' %}" alt="Apartments" >
						<h1 class="site-title"><a>SearchMyAgent</a></h1>
						<small class="site-description">Live better</small>
							</a>
					</div>
							</div>
						</nav>
					</div>
        </div>
    </header>

    <div class="main">
   <!-- MultiStep Form -->
{% if Name %}
		<div class="container">
			<div class="row justify-content-center">
				<h1  class="headtitle " >Thanks {{ Name }}!</h1>
				<p class="tagline ">We recived your information and will respond shortly</p>
             </div>
			</div>
{% else %}
<form id="booking-form" action="{% url 'agentFinder:selling_forms_save' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

	<div class="formcontent">
		<div class="tab-content">
			<div class="tab-pane" id="step1">
				<ul>
					<li>
            <label>What is the full address of the
				property you want to sell?</label>
            <div class="errorTxt"></div>
            <input type="text" id="search_input" name="address" placeholder="Enter address">
				 </li>

				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn1" type="button">Prev</button>
						<button class="next-btn next-btn1" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step2">
				<ul>
					<li>
            <label>What is your property type?</label>
            <div class="errorTxt"></div>
            <select name="properType" required>
              <option value="">Select</option>
              <option value="Single Family">Single Family</option>
              <option value="Condo">Condo</option>
              <option value="land or lot">land or lot</option>
              <option value="Mobile Home">Mobile Home</option>
              <option value="Townhome">Townhome</option>
              <option value="Commercial">Commercial</option>

					</select>
				 </li>
				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn2" type="button">Prev</button>
						<button class="next-btn next-btn2" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step3">
				<ul>
					<li>
            <label>What is your target sale price?</label>
            <div class="errorTxt"></div>
            <select name="tgSale" required>
              <option value="">Select</option>
              <option value="$50k-$100k">$50k-$100k</option>
              <option value="$100k-$150k">$100k-$150k</option>
              <option value="$150k-$200k">$150k-$200k</option>
              <option value="$200k-$250k">$200k-$250k</option>
              <option value="$250k-$300k">$250k-$300k</option>
              <option value="$300k-$350k">$300k-$350k</option>
              <option value="$350k-$400k">$350k-$400k</option>
              <option value="$400k-$450k">$400k-$450k</option>
              <option value="$450k-$500k">$450k-$500k</option>
              <option value="$500k-$550k">$500k-$550k</option>

					</select>
				 </li>
				 <li style="list-style: none; display: inline">
					 <button class="prev-btn prev-btn3" type="button">Prev</button>
						<button class="next-btn next-btn3" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step4">
				<ul>

					<li>
            <label>How soon are you looking to sell?</label>
            <div class="errorTxt"></div>
            <select name="soonTime">
              <option value="">Select</option>
              <option value="0-3 Months">0-3 Months</option>
				<option value="3-6 Months">3-6 Months</option>
				<option value="6-12 Months">6-12 Months</option>
				<option value="Over 1 Year">Over 1 Year</option>
            	  </select>
				  </li>

					<li class="buttons">
						<button class="prev-btn prev-btn4" type="button">Prev</button>
						<button class="next-btn next-btn4" type="button">Next</button>
					</li>
				</ul>
			</div>
			<div class="tab-pane" id="step5">
				<ul>


					<li>
            <label>Let's connect you with the best agent in your area</label>
            <div class="errorTxt"></div>
            <input type="text" name="fname" placeholder="Full Name">
          </li>
					<li>
						<div class="errorTxt"></div>
					  <input type="text" name="phone" placeholder="Phone">
					</li>
					<li>
						<div class="errorTxt"></div>
					  <input type="email" name="email" placeholder="email">
					</li>
					<li>
						<button class="prev-btn prev-btn5" type="button">Prev</button>
						<button class="submit-btn" type="submit">Find an Agent</button>
					</li>
				</ul>
			</div>
		</div>

		<div class="progress-wrap">
			<div class="line-progress-bar">
				<div class="line"></div>
				<ul class="checkout-bar">
					<li class="progressbar-dots active"><span>step 1</span></li>
					<li class="progressbar-dots"><span>step 2</span></li>
					<li class="progressbar-dots"><span>Final step</span></li>
				</ul>
			</div>
		</div>

		<div id="loader" style="display: none;">
			<img src="//d2erq0e4xljvr7.cloudfront.net/assets/img/ring.svg">
		</div>
		</div>
	</form>
<!-- /.MultiStep Form -->

{% endif %}
    <!-- JS -->

    <script src="{% static 'agentFinder/js/main.js' %}" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>